"""Configuration loading and path resolution for loki."""

from pathlib import Path

import yaml
from pydantic import BaseModel

REPO_ROOT = Path(__file__).parent.parent


class KiwixFile(BaseModel):
    """A ZIM file entry from the configuration.

    Attributes
    ----------
    name : str
        Human-readable label for the ZIM file.
    url : str
        Direct download URL for the .zim file.
    """

    name: str
    url: str


class PortsConfig(BaseModel):
    """Host port assignments for Docker Compose services.

    Attributes
    ----------
    caddy : int
        Host port for the Caddy reverse proxy. Default is 80.
    kiwix : int
        Host port for the Kiwix server. Default is 8080.
    ollama : int
        Host port for the Ollama API. Default is 11434.
    """

    caddy: int = 80
    kiwix: int = 8080
    ollama: int = 11434


class LokiConfig(BaseModel):
    """Top-level configuration for the loki stack.

    Attributes
    ----------
    url : str
        Local hostname to expose via Caddy. Default is ``"loki.local"``.
    ports : PortsConfig
        Host port assignments for each service.
    kiwix_files : list of KiwixFile
        ZIM files to download during setup.
    ollama_models : list of str
        Ollama model tags to pull before starting the stack.
    """

    url: str = "loki.local"
    ports: PortsConfig = PortsConfig()
    kiwix_files: list[KiwixFile] = []
    ollama_models: list[str] = []


def load_config(path: Path | None = None) -> LokiConfig:
    """Load and validate config.yaml, returning a LokiConfig instance.

    Parameters
    ----------
    path : Path or None, optional
        Explicit path to the config file. If ``None``, defaults to
        ``<repo_root>/config.yaml``.

    Returns
    -------
    LokiConfig
        Validated configuration parsed from the YAML file.
    """
    config_path = path or REPO_ROOT / "config.yaml"
    with open(config_path) as f:
        data = yaml.safe_load(f) or {}
    return LokiConfig.model_validate(data)


def kiwix_dir() -> Path:
    """Return the absolute path to the kiwix data directory."""
    return REPO_ROOT / "data" / "kiwix"


def caddyfile_path() -> Path:
    """Return the absolute path to the Caddyfile."""
    return REPO_ROOT / "Caddyfile"


def env_file_path() -> Path:
    """Return the absolute path to the generated .env file."""
    return REPO_ROOT / ".env"


def build_caddyfile(caddy_url: str) -> str:
    """Return the Caddyfile content that routes a URL to Open WebUI.

    Parameters
    ----------
    caddy_url : str
        Local hostname to expose (e.g. ``"loki.local"``).

    Returns
    -------
    str
        Caddyfile configuration as a string.
    """
    return (
        f"# Route traffic for the configured local URL to Open WebUI.\n"
        f"http://{caddy_url} {{\n"
        f"    reverse_proxy open-webui:8080\n"
        f"}}\n"
    )


def build_env_file(ports: PortsConfig) -> str:
    """Return .env file content with port assignments for Docker Compose.

    Parameters
    ----------
    ports : PortsConfig
        Port assignments to write into the environment file.

    Returns
    -------
    str
        Contents of the .env file as a string.
    """
    return (
        "# Generated by `loki setup` — do not edit by hand.\n"
        f"CADDY_PORT={ports.caddy}\n"
        f"KIWIX_PORT={ports.kiwix}\n"
        f"OLLAMA_PORT={ports.ollama}\n"
    )
