"""Configuration loading and path resolution for loki."""

from pathlib import Path

import yaml
from pydantic import BaseModel

REPO_ROOT = Path(__file__).parent.parent


class KiwixFile(BaseModel):
    name: str
    url: str


class PortsConfig(BaseModel):
    caddy: int = 80
    kiwix: int = 8080
    ollama: int = 11434


class LokiConfig(BaseModel):
    url: str = "loki.local"
    ports: PortsConfig = PortsConfig()
    kiwix_files: list[KiwixFile] = []
    ollama_models: list[str] = []


def load_config(path: Path | None = None) -> LokiConfig:
    """Load and validate config.yaml, returning a LokiConfig instance."""
    config_path = path or REPO_ROOT / "config.yaml"
    with open(config_path) as f:
        data = yaml.safe_load(f) or {}
    return LokiConfig.model_validate(data)


def kiwix_dir() -> Path:
    """Return the absolute path to the kiwix data directory."""
    return REPO_ROOT / "data" / "kiwix"


def caddyfile_path() -> Path:
    """Return the absolute path to the Caddyfile."""
    return REPO_ROOT / "Caddyfile"


def env_file_path() -> Path:
    """Return the absolute path to the generated .env file."""
    return REPO_ROOT / ".env"


def build_caddyfile(caddy_url: str) -> str:
    """Return the Caddyfile content for the given URL."""
    return (
        f"# Route traffic for the configured local URL to Open WebUI.\n"
        f"http://{caddy_url} {{\n"
        f"    reverse_proxy open-webui:8080\n"
        f"}}\n"
    )


def build_env_file(ports: PortsConfig) -> str:
    """Return .env file content with port assignments for Docker Compose."""
    return (
        "# Generated by `loki setup` — do not edit by hand.\n"
        f"CADDY_PORT={ports.caddy}\n"
        f"KIWIX_PORT={ports.kiwix}\n"
        f"OLLAMA_PORT={ports.ollama}\n"
    )
