"""Assemble the llama-server models preset from per-model ``preset.ini`` files."""

import configparser
from pathlib import Path

PRESET_FILENAME = "preset.ini"

# Preset options whose values are file paths, resolved against the preset's directory
PATH_OPTIONS = ("model", "model-draft", "mmproj", "chat-template-file")


class PresetError(Exception):
    """Raised when a model preset is malformed or references a missing file."""


def _format_value(value: str | int | float | bool) -> str:
    """Render a config value the way llama-server's INI parser expects it."""
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _read_preset(path: Path) -> configparser.ConfigParser:
    """Parse one ``preset.ini`` keeping option names case-sensitive."""
    parser = configparser.ConfigParser(
        delimiters=("=",),
        comment_prefixes=(";", "#"),
        interpolation=None,
        default_section="__unused__",
    )
    parser.optionxform = str  # type: ignore[method-assign, assignment]
    try:
        with path.open() as f:
            parser.read_file(f)
    except configparser.Error as exc:
        raise PresetError(f"{path}: {exc}") from exc
    return parser


def discover_presets(models_dir: Path) -> list[Path]:
    """Return every ``<models_dir>/<model>/preset.ini``, sorted by path.

    Parameters
    ----------
    models_dir : Path
        Directory whose immediate subdirectories hold one model each.

    Returns
    -------
    list of Path
        Preset files found one level below ``models_dir``.
    """
    return sorted(models_dir.glob(f"*/{PRESET_FILENAME}"))


def build_models_preset(
    models_dir: Path, defaults: dict[str, str | int | float | bool]
) -> tuple[str, list[str]]:
    r"""Return the combined models preset and the model ids it declares.

    Each ``preset.ini`` contributes its sections unchanged except that relative
    file paths become absolute paths inside the preset's own directory.
    ``defaults`` becomes the global ``[*]`` section shared by every model.

    Parameters
    ----------
    models_dir : Path
        Absolute directory holding one subdirectory per model.
    defaults : dict of str to scalar
        llama-server options written to the global section.

    Returns
    -------
    preset : str
        INI text for ``llama-server --models-preset``.
    model_ids : list of str
        Section names in the order they appear in ``preset``.

    Raises
    ------
    PresetError
        If a preset cannot be parsed, declares the global section, repeats a
        model id, omits ``model``, or points at a file that does not exist.

    Examples
    --------
    >>> import tempfile
    >>> root = Path(tempfile.mkdtemp())
    >>> (root / "tiny").mkdir()
    >>> (root / "tiny" / "tiny.gguf").touch()
    >>> _ = (root / "tiny" / "preset.ini").write_text("[tiny]\nmodel = tiny.gguf\n")
    >>> text, ids = build_models_preset(root, {"n-gpu-layers": 99})
    >>> ids
    ['tiny']
    >>> f"model = {root}/tiny/tiny.gguf" in text
    True
    """
    lines = [
        "; Generated by loki from config.yaml and each model's preset.ini; do not edit by hand",
        "version = 1",
        "",
        "[*]",
        *(f"{key} = {_format_value(value)}" for key, value in defaults.items()),
    ]
    model_ids: list[str] = []

    for path in discover_presets(models_dir):
        parser = _read_preset(path)

        for model_id in parser.sections():
            # Reject sections that would collide with the global or another model
            if model_id == "*":
                raise PresetError(f"{path}: global settings belong in config.yaml llama.defaults")
            if model_id in model_ids:
                raise PresetError(f"{path}: model id '{model_id}' is already defined")

            options = dict(parser[model_id])
            if "model" not in options:
                raise PresetError(f"{path}: [{model_id}] has no 'model' option")

            # Anchor file options to the preset's directory and require them to exist
            for key in PATH_OPTIONS:
                if key not in options:
                    continue
                target = Path(options[key]).expanduser()
                if not target.is_absolute():
                    target = path.parent / target
                if not target.is_file():
                    raise PresetError(f"{path}: [{model_id}] {key} not found: {target}")
                options[key] = str(target)

            lines += ["", f"[{model_id}]", *(f"{key} = {value}" for key, value in options.items())]
            model_ids.append(model_id)

    return "\n".join(lines) + "\n", model_ids
